baseURL = "https://jasin.atipi.it/"
languageCode = "en-us"
title = "Atipi Jasin"
theme = "fixit"
pagination.pagerSize = 12
copyright = ""
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[markup]
  [markup.highlight]
    style='xcode'
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menu]
  [[menu.main]]
    identifier = "apps"
    parent = ""
    pre = ""
    post = ""
    name = "Apps"
    url = "/apps"
    title = "Apps"
    weight = 1
    [menu.main.params]
      class = ""
      draft = false
      icon = "fa-solid fa-gamepad"
      type = ""

  [[menu.main]]
    identifier = "posts"
    parent = ""
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = "Posts"
    weight = 2
    [menu.main.params]
    class = ""
    draft = false
    icon = "fa-solid fa-newspaper"
    type = ""

[params]
math = true
capitalizeTitles = false
description = "Atipi Jasin's personal Website and Blog"
  [params.header]
    desktopMode = "sticky"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      pre = ""
      post = ""
      typeit = false 
    [params.header.subtitle]
      name = ""
      typeit = false 

  [params.home]
    [params.home.profile]
      enable = true 
      avatarURL = "https://avatars.githubusercontent.com/u/30267143"
      title = "Atipi Jasin"
      subtitle = "ğŸ¾ğŸ¹ğŸ“ğŸ‘¾ğŸ§—ğŸ’»ğŸ“šğŸ—»"
      typeit = true
      social = true
      disclaimer = "Software Engineer"
    [params.home.posts]
      enable = true
      paginate = 6

  [params.typeit]
    speed = 200
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1
    loop = true 

  [params.social]
    GitHub = "atipijasin"
    Linkedin = "jasinatipi"
    Twitter = "atipijasin"
    Instagram = "atipijasin"
    Telegram = "jasin_atipi"
    Medium = "jasin.atipi"
    Devto = "atipij"
    Email = "jasin@atipi.it"
    Goodreads = "177467161-jasin-atipi"
    RSS = false
